### ISSUE TITLE
Menampilkan Data Dosen

### ISSUE THREAD

**Issue by wdysr** [wdysr/Proyek-Web-19108002-2020#1]
Membuat source code untuk menampilkan data dosen dengan menggunakan CodeIgniter, file terdiri dari :
- Controller : data_dosen
- Model : m_dosen
- View : v_dosen

**Comment by yaddarabullah** [comment]
Ok, sudah saya terima invitation nya

**Comment by fitriadewi09** [comment]
Source code yang telah Anda buat sudah selesai diperiksa. 
Menurut saya, source code yang dibuat sudah baik dan benar sehingga menghasilkan tampilan halaman data dosen yang menarik dan juga rapih karena menggunakan bootstrap. File-file code yang telah dipush ke dalam branch Dosen juga sudah lengkap tanpa ada kekurangan. Dari hasil penilaian yang telah saya buat, Wiwied Widyasari berhak mendapatkan nilai **95** untuk proyek ini. Terima kasih.

**Comment by wdysr** [comment]
Baik, terima kasih untuk Pak Yadda yang sudah menerima invitation dan Fitria Dewi yang sudah menyempatkan waktunya untuk memberikan comment serta penilaian untuk saya. Terima kasih banyak.
